#!/bin/bash

# general
alias rm="rm -i"
alias cp="cp -iv"
alias ls="ls --color=auto -h"
alias less="less -S"
alias grep="grep --color=auto"
alias pacman="pacman --color auto"
alias ranger="ranger --choosedir=$HOME/.config/rangerdir; LASTDIR='cat $HOME/.config/rangerdir'; cd $LASTDIR"
alias say='echo "$1" | espeak -s 120 2>/dev/null'
alias du="du -h"
alias df="df -h"
alias transfer="android-file-transfer"
alias 42="cd /home/azeddine/development/42cursus"
alias v="nvim"
alias watch="watch -n 1"

# config dirs
#alias dwmdir="cd /home/azeddine/.local/share/dwm"

# git
alias dfs="/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
alias dfsstatus="dfs status -uno"
